#pragma once
#include <sampapi/sampapi.h>
#include <sampapi/AimStuff.h>
#include <sampapi/Animation.h>
#include <sampapi/CActor.h>
#include <sampapi/CActorPool.h>
#include <sampapi/CAudio.h>
#include <sampapi/CAudioStream.h>
#include <sampapi/CCamera.h>
#include <sampapi/CChat.h>
#include <sampapi/CChatBubble.h>
#include <sampapi/CConfig.h>
#include <sampapi/CDeathWindow.h>
#include <sampapi/CDialog.h>
#include <sampapi/CEntity.h>
#include <sampapi/CFont.h>
#include <sampapi/CFonts.h>
#include <sampapi/CGame.h>
#include <sampapi/CGangZonePool.h>
#include <sampapi/CHelpDialog.h>
//#include <sampapi/CHttpClient.h>
#include <sampapi/CInput.h>
#include <sampapi/CLabel.h>
#include <sampapi/CLabelPool.h>
#include <sampapi/CLicensePlate.h>
#include <sampapi/CLocalPlayer.h>
#include <sampapi/CMatrix.h>
#include <sampapi/CMenu.h>
#include <sampapi/CMenuPool.h>
#include <sampapi/CNetGame.h>
#include <sampapi/CNetStats.h>
#include <sampapi/CObject.h>
#include <sampapi/CObjectMaterialText.h>
#include <sampapi/CObjectPool.h>
#include <sampapi/CObjectSelection.h>
#include <sampapi/Commands.h>
#include <sampapi/ControllerState.h>
#include <sampapi/CPed.h>
#include <sampapi/CPickupPool.h>
#include <sampapi/CPlayerInfo.h>
#include <sampapi/CPlayerPool.h>
#include <sampapi/CPlayerTags.h>
#include <sampapi/CRect.h>
#include <sampapi/CRemotePlayer.h>
#include <sampapi/CScoreboard.h>
#include <sampapi/CSpawnScreen.h>
#include <sampapi/CSrvNetStats.h>
#include <sampapi/CTextDraw.h>
#include <sampapi/CTextDrawPool.h>
#include <sampapi/CTextDrawSelection.h>
#include <sampapi/CVector.h>
#include <sampapi/CVehicle.h>
#include <sampapi/CVehiclePool.h>
#include <sampapi/Debug.h>
#include <sampapi/DebugScript.h>
#include <sampapi/Exception.h>
#include <sampapi/GUI.h>
#include <sampapi/InputHandler.h>
#include <sampapi/KeyStuff.h>
#include <sampapi/RPC.h>
#include <sampapi/Scripting.h>
#include <sampapi/Settings.h>
#include <sampapi/SpecialAction.h>
#include <sampapi/Synchronization.h>
#include <sampapi/VehicleSelection.h>

namespace samp = sampapi::v037r3; // Samp Version